- CONTRIBUTING.rst
- docs/user_guide.rst
- fix instructions in user-guide to visualize example circuit
- add note on requirements for building docs
> Comp 369 fix example in user guide

- CHANGELOG.rst
- src/qiskit_iqm/qiskit_to_iqm.py
- tests/test_qiskit_to_iqm.py
Allow Qiskit on IQM to serialize barrier operations.
> COMP-323 allow barrier operations in qiskit-on-iqm

- CHANGELOG.rst
- setup.cfg
- src/qiskit_iqm/iqm_job.py
- tests/test_iqm_job.py
IQM Client 3.2 introduced a new function `get_run_status` which returns the status of a job, but, unlike `get_run`, returns status only, and never returns measurement results. 
Previously, qiskit-on-iqm's `IQMJob.status()` function would return the status, but if the status was ready, it would also save the measurement results in memory behind the scenes. As a result, the consequent `IQMJob.result()` function would return the results instantaneously, without calling the client. 
With the current change, `IQMJob.status()` uses the new function of IQM Client, and thus does not save results behind the scenes when user requests the status.
> Use get_run_status instead of get_run to retrieve status

- AUTHORS.rst
- CHANGELOG.rst
- docs/user_guide.rst
- setup.cfg
- src/qiskit_iqm/iqm_backend.py
- tests/test_iqm_backend.py
[IQM Client 6.1](https://github.com/iqm-finland/iqm-client/commit/45654f63d3f363f2996d143f145a38cd19785b35) now allows to specify a `calibration_set_id`. This PR updates qiskit-on-iqm accordingly.
> Add optional calibration_set_id parameter to IQMBackend.run

- .github/workflows/ci.yml
- CHANGELOG.rst
- setup.cfg
- src/qiskit_iqm/iqm_backend.py
- src/qiskit_iqm/iqm_job.py
- tests/test_iqm_job.py
Qiskit circuit class contains attribute`QuantumCircuit.metadata`: an arbitrary key value metadata to associate with the circuit ([see docs](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html?highlight=quantumcircuit#qiskit.circuit.QuantumCircuit.metadata)). `IQMBackend.run()` takes that data and populates `IQMJob.circuit_metadata`; later, when results are retrieved via `IQMJob.result()`, the same data is copied into the result in. However, this only works if `IQMBackend.run()` and `IQMJob.result()` are called in the same Python session.
A new version of the IQM server returns a complete copy of the original request; [IQM Client version 10](https://github.com/iqm-finland/iqm-client/pull/65) implements related changes. 
This Qiskit-on-IQM PR takes advantage of that …
> Populate circuit_metadata from job results

- docs/user_guide.rst
- examples/bell_measure.py
* Make the server URL parameter name consistent with the documentation and other libraries
* Remove an option unsuitable for the "Hello, world!" example
* Update the mock environment terminology
> Clarify parameters, update terminology

- CHANGELOG.rst
- src/qiskit_iqm/iqm_job.py
- src/qiskit_iqm/iqm_provider.py
- tests/test_iqm_job.py
- tests/test_iqm_provider.py
This MR fixes two small issues:
* Handle case where heralding returns zero shots
* Handle cal set id both as str and UUID
> Bugfix: Handle case where heralding returns zero shots

- CHANGELOG.rst
- src/qiskit_iqm/fake_backends/iqm_fake_backend.py
- tests/fake_backends/test_iqm_fake_backend.py
Errors to two-qubit `CZ` gates were only applied for one specific order of the qubit arguments in the gate construction. But the error should be applied independent of this order since the gate is symmetric in control and target qubit.
Changes:
- Added reverse qubit order in error construction in `iqm_fake_backend.py`.
- Added assertion to test case `test_noise_model_contains_all_errors` in `test_iqm_fake_backend.py`.
> Fixed 2QB gate error depending on qubit order

- CHANGELOG.rst
- pyproject.toml
- src/qiskit_iqm/iqm_backend.py
- src/qiskit_iqm/iqm_job.py
- src/qiskit_iqm/iqm_provider.py
- tests/conftest.py
- tests/fake_backends/test_fake_adonis.py
- tests/test_iqm_job.py
- tests/test_iqm_provider.py
* **Upgrade to qiskit ~= 0.44.1.** Qiskit has changed a lot since last time our dependency was bumped, so its time to follow along. Some notable changes:
* There is no `qiskit-terra` anymore - it was just merged into the main `qiskit` package.
* `qiskit-aer` no longer gets installed by default when installing qiskit, so now we have to have explicit dependency on it, since fake backend uses it.
* When binding numeric values to `ParameterExpression`s, the result is actually the number itself. Previously it would still remain a `ParameterExpression`, that contained a number and you had to cast it to float.
* Make the ``max_circuits`` property of ``IQMBackend`` user-configurable. Explained in the inline comment.
* Implement ``error_message`` method for ``IQMJob``. Some code in …
> Some unrelated small updates and fixes

- CHANGELOG.rst
- docs/user_guide.rst
- src/iqm/qiskit_iqm/iqm_job.py
- src/iqm/qiskit_iqm/iqm_provider.py
- tests/test_iqm_provider.py
- Adds a new option called `circuit_callback` to `IQMBackend`. Description and motivation is in the user guide.
- Unknown options passed to backend now cause an error. Previously they were just silently ignored, which was not good. E.g. if you wanted to specify custom calset ID, but you made a typo in the name of the option, it would get ignored and the default calibration set would be still used. And you would be left wondering why your calibration set is not being used. Now you will immediately get error that you have not supplied a correct option.
- Handling of options is now improved a bit and the code is easier to read and consume.
- Fix the type of ``date`` in result object. Qiskit expects it to be string. It was datetime before.
- ``IQMBackend`` can now serialize `x`, `rx`, `y` and …
> IQMBackend improvements

- CHANGELOG.rst
- pyproject.toml
- src/iqm/qiskit_iqm/iqm_provider.py
- tests/test_iqm_provider.py
- https://github.com/iqm-finland/qiskit-on-iqm/pull/80 introduced errors for scenarios when user provides unknown options to the backend. This is too restrictive and causes some unnecessary work in some cases, e.g. running QV experiments. Warning the user about unknown options should be enough. 
- `pylint` released a new major version overnight, and our test dependency on `pytest_pylint` installs it, then causes errors during the running of tests, because of incompatibility. Since `pytest_pylint` does not yet have an upgrade to support this new version, I had to pin the pylint version in the dependencies as well.
> Emit warning instead of raising error for unknown options

- .github/workflows/publish.yml
- .github/workflows/tag_and_release.yml
- CHANGELOG.rst
- pyproject.toml
- Separate ```push_to_pypi``` job into two jobs: ```build``` and ```push_to_pypi```
- Use ```publish``` workflow file from current feature branch rather than ```main``` branch
- Do not use ```tox``` in ```publish``` workflow to build and upload package
- Remove ```twine``` dependency
- Remove references to PyPI secrets
> Use GitHub Action Trusted Publisher for PyPI publishing

- README.rst
Sphinx roles like :file: are not allowed in README.rst which becomes the long_description in PyPI.
> Fix publishing to PyPI

- CHANGELOG.rst
- src/iqm/qiskit_iqm/examples/transpile_example.py
Previously it would result in error `qiskit.transpiler.exceptions.TranspilerError: 'Number of qubits greater than device.'` when running on a device with less than 5 qubits. Now it works also when less than 5 qubits are available.
> Fix transpile example

- src/iqm/qiskit_iqm/iqm_transpilation.py
This PR adds a `=` sign to the docstring of the optimize single qubit gates function
> add missing character to docs

- CHANGELOG.rst
- docs/user_guide.rst
- pyproject.toml
- src/iqm/qiskit_iqm/iqm_provider.py
- tests/test_iqm_provider.py
Requires https://github.com/iqm-finland/iqm-client/pull/129, tests will fail until it is merged.
> Allow inspecting a RunRequest without submitting it for execution

- CHANGELOG.rst
- docs/user_guide.rst
- tests/test_iqm_transpilation.py
* Fix broken code in the user guide.
* Fix contact link.
> More user guide updates.

- .github/workflows/publish.yml
- CHANGELOG.rst
Does the same thing as https://github.com/iqm-finland/iqm-client/pull/133.
Here I didn't add documentation about the alternative `git clone` options, because the repository size is not as big as iqm-client (~50MB vs ~500MB), so it's still pretty fast to clone normally.
> Remove unnecessary build files when publishing documentation

- CHANGELOG.rst
- src/iqm/qiskit_iqm/iqm_provider.py
- tests/test_iqm_provider.py
- Extract most of the instruction conversion logic from a backend method to a pure function. The old behavior is not changed but  GitHub does not show the changes neatly.
> Extract instruction serialization

- CHANGELOG.rst
- docs/user_guide.rst
- src/iqm/qiskit_iqm/examples/resonance_example.py
- src/iqm/qiskit_iqm/iqm_job.py
- tests/test_iqm_backend.py
- tests/test_iqm_provider.py
- tests/test_resonance_example.py
- tests/utils.py
- This fixes compatibility with iqm-client APIVariant V2.
- support iqm-client 20.5 in unit tests
- make resonance example testable, an improvement over @manzanillo implementation from https://github.com/iqm-finland/qiskit-on-iqm/pull/131
- cherry-pick resonance guide by @freetonik from https://github.com/iqm-finland/qiskit-on-iqm/pull/131
I suggest also closing https://github.com/iqm-finland/qiskit-on-iqm/pull/131 if this one is merged.
> Do not use original request directly

- docs/user_guide.rst
> Fix spelling mistake in user guide

- docs/user_guide.rst
- src/iqm/qiskit_iqm/iqm_provider.py
This pull request updates the authentication process in `IQMProvider` and improves the user guide to better reflect the usage of IQM Resonance.
Changes:
* Updated IQMProvider to mention authentication option for IQM Resonance 
* Mentioned the support for the token parameter in the User guide.
* Added separating headlines for IQM Resonance and on-prem QCs
> Reflect Resonance authentication in docs better

- CHANGELOG.rst
- src/iqm/qiskit_iqm/iqm_transpilation.py
- tests/fake_backends/test_fake_deneb.py
- tests/test_iqm_transpilation.py
Bugfix in ``IQMOptimizeSingleQubitGates`` where the angles are not properly computed for circuits with prx gates on qubits holding a resonator state, i.e. circuits that require running without move gate validation.
> SW-803: Bugfix in IQMOptimizeSingleQubitGates where the angles are not properly computed 

- src/iqm/qiskit_iqm/iqm_naive_move_pass.py
- src/iqm/qiskit_iqm/iqm_provider.py
This PR introduces a warning in case a facade backend name is used that does not exist, I did not add a release note, it can be released with whatever else comes next
> add warning when unknown facade name is used

- CHANGELOG.rst
- src/iqm/qiskit_iqm/iqm_transpilation.py
- tests/conftest.py
- tests/test_iqm_transpilation.py
* `IQMOptimizeSingleQubitGates` now accepts `delay` operations.
> Bugfix: transpile() fails in a circuit with delay ops.

- CHANGELOG.rst
- src/iqm/qiskit_iqm/iqm_job.py
We will have other job statuses in the future, and the client code should tolerate them even if it does not strictly need them.
This is mostly for situations where the server is updated but the client version is not.
> Handle unknown job statuses

- CHANGELOG.rst
- tests/test_iqm_backend.py
- tests/test_iqm_provider.py
- tests/utils.py
* Fix error in `test_facade_backend_raises_error_on_remote_execution_fail`
* Fix `"Could not verify IQM Client compatibility with the server"` warnings in unit tests.
> Fix unit tests compatibility with latest iqm-client
